export enum PaymentProvider {
  TOSS_PAYMENTS = "TOSS_PAYMENTS",
}

export enum PaymentMethod {
  CARD = "CARD",
  TOSS_PAY = "TOSS_PAY",
  NAVER_PAY = "NAVER_PAY",
  KAKAO_PAY = "KAKAO_PAY",
  SAMSUNG_PAY = "SAMSUNG_PAY",
  APPLE_PAY = "APPLE_PAY",
  TRANSFER = "TRANSFER",
  VIRTUAL_ACCOUNT = "VIRTUAL_ACCOUNT",
}

export enum TossPaymentStatus {
  READY = "READY",
  IN_PROGRESS = "IN_PROGRESS",
  WAITING_FOR_DEPOSIT = "WAITING_FOR_DEPOSIT",
  DONE = "DONE",
  CANCELED = "CANCELED",
  PARTIAL_CANCELED = "PARTIAL_CANCELED",
  ABORTED = "ABORTED",
  EXPIRED = "EXPIRED",
}
